### ISSUE TITLE
为什么展示页面都需要iframe来展示？

### ISSUE THREAD

**Issue by Niofh** [lx544690189/scorpio-h5-design#2]
为什么展示页面都需要iframe来展示？这个是什么原理，打算准备学习一下可视化拖拽，看到你这个项目我觉得挺好的，准备学习您的源码。还想请教你学习这些需要准备哪些技术

**Comment by lx544690189** [comment]
iframe是为了js、css隔离，移动端vw单位适配。技术的话前端没什么特别难的点，后端node写的可以学习下
